import type { Service, ServiceCategoryMeta, ServicesData, ServicesStats } from '../types/servicesTypes';

export const demoServicesCategories: ServiceCategoryMeta[] = [
  {
    id: 'FOR_PEOPLE',
    label: 'For People & Families',
    description: 'Report a need, find shelter and reconnect with loved ones.',
  },
  {
    id: 'FOR_VOLUNTEERS',
    label: 'For Volunteers',
    description: 'Join the response, verify reports and support your community.',
  },
  {
    id: 'FOR_ORGANIZATIONS',
    label: 'For NGOs & Government',
    description: 'Coordinate relief, manage deliveries and prove impact.',
  },
];

export const demoServicesStats: ServicesStats = {
  provinces: 7,
  districts: 77,
  volunteers: 12500,
  needsVerified: 2840,
  shelters: 360,
};

export const demoServices: Service[] = [
  // ── For People & Families ──────────────────────────────────────────
  {
    _id: 'svc-report',
    title: 'Report a Need',
    ne: 'आवश्यकता रिपोर्ट गर्नुहोस्',
    description: 'Describe what your community needs — food, water, shelter, medical care or evacuation — and responders will see it in real time.',
    features: ['Works offline, auto-syncs online', 'Add photos & voice memos', 'Track status until resolved'],
    icon: 'report',
    cta: { label: 'REPORT A NEED', to: '/report' },
    category: 'FOR_PEOPLE',
    popular: true,
    tint: 'bg-critical/10 text-critical',
    accent: 'bg-critical hover:bg-critical/90',
  },
  {
    _id: 'svc-map',
    title: 'Live Relief Map',
    ne: 'प्रत्यक्ष राहत नक्सा',
    description: 'Explore verified needs, open shelters and active responses on one map of Nepal updated in real time.',
    features: ['Filter by need type & district', 'Capacity-aware shelter markers', 'Works on mobile & desktop'],
    icon: 'map',
    cta: { label: 'VIEW LIVE MAP', to: '/map' },
    category: 'FOR_PEOPLE',
    popular: true,
    tint: 'bg-primary/10 text-primary',
    accent: 'bg-primary hover:bg-primary-dark',
  },
  {
    _id: 'svc-shelter',
    title: 'Find a Shelter',
    ne: 'आश्रय खोज्नुहोस्',
    description: 'Locate open shelters near you and see live occupancy, capacity and directions before you move.',
    features: ['Live capacity bar', 'Listed by district', 'Offline-friendly search'],
    icon: 'shelter',
    cta: { label: 'FIND SHELTERS', to: '/shelters' },
    category: 'FOR_PEOPLE',
    tint: 'bg-secondary/10 text-secondary',
    accent: 'bg-secondary hover:bg-secondary/90',
  },
  {
    _id: 'svc-missing',
    title: 'Missing Persons',
    ne: 'बेपत्ता व्यक्तिहरू',
    description: 'Report missing family members or search community submissions to help reconnect families after a disaster.',
    features: ['Upload a recent photo', 'Get notified on match', 'Private, yet shareable'],
    icon: 'missing',
    cta: { label: 'SEARCH & REPORT', to: '/missing-persons' },
    category: 'FOR_PEOPLE',
    popular: true,
    tint: 'bg-ink/10 text-ink',
    accent: 'bg-ink hover:bg-ink/90',
  },
  {
    _id: 'svc-emergency',
    title: 'Emergency Support',
    ne: 'आपतकालीन सहयोग',
    description: 'Signal life-threatening needs so volunteers and responders can prioritize and reach you first.',
    features: ['One-tap urgent report', 'Critical priority queue', 'Direct responder alerts'],
    icon: 'emergency',
    cta: { label: 'REQUEST URGENT HELP', to: '/report' },
    category: 'FOR_PEOPLE',
    popular: true,
    tint: 'bg-critical/15 text-critical',
    accent: 'bg-critical hover:bg-critical/90',
  },

  // ── For Volunteers ─────────────────────────────────────────────────
  {
    _id: 'svc-volunteer',
    title: 'Become a Volunteer',
    ne: 'स्वयंसेवक बन्नुहोस्',
    description: 'Join the community network that verifies reports and delivers help on the ground across Nepal.',
    features: ['Simple registration', 'Pick your district', 'Badges & leaderboards'],
    icon: 'volunteer',
    cta: { label: 'JOIN THE RESPONSE', to: '/register' },
    category: 'FOR_VOLUNTEERS',
    tint: 'bg-success/10 text-success',
    accent: 'bg-success hover:bg-success/90',
  },
  {
    _id: 'svc-verify',
    title: 'Verify Reports',
    ne: 'रिपोर्ट प्रमाणित गर्नुहोस्',
    description: 'Confirm real needs near you so verified reports reach organizations first and help is distributed fairly.',
    features: ['Nearby verification queue', 'Photo proof', 'Growing trust score'],
    icon: 'verify',
    cta: { label: 'START VERIFYING', to: '/register' },
    category: 'FOR_VOLUNTEERS',
    tint: 'bg-tertiary/10 text-tertiary',
    accent: 'bg-tertiary hover:bg-tertiary/90',
  },
  {
    _id: 'svc-reports',
    title: 'Browse All Needs',
    ne: 'आवश्यकता हेर्नुहोस्',
    description: 'Follow every reported need in your community and jump in the moment help is requested.',
    features: ['Filter by urgency', 'Sort by district', 'Live updates'],
    icon: 'reports',
    cta: { label: 'VIEW ALL NEEDS', to: '/reports' },
    category: 'FOR_VOLUNTEERS',
    tint: 'bg-warning/10 text-warning',
    accent: 'bg-warning hover:bg-warning/90',
  },
  {
    _id: 'svc-track',
    title: 'Track Responses',
    ne: 'प्रतिक्रिया ट्र्याक गर्नुहोस्',
    description: 'Watch claims, deliveries and resolutions unfold in real time so no family is left behind.',
    features: ['Claim timeline', 'Delivery proof gallery', 'Transparent status board'],
    icon: 'track',
    cta: { label: 'FOLLOW RESPONSES', to: '/map' },
    category: 'FOR_VOLUNTEERS',
    tint: 'bg-secondary/10 text-secondary',
    accent: 'bg-secondary hover:bg-secondary/90',
  },

  // ── For NGOs & Government ──────────────────────────────────────────
  {
    _id: 'svc-ngo',
    title: 'NGO Coordination',
    ne: 'संस्था समन्वय',
    description: 'Claim verified needs, assign teams, manage deliveries and prove impact with photo evidence.',
    features: ['Smart claim queue', 'Delivery planning', 'Impact reports'],
    icon: 'ngo',
    cta: { label: 'FOR ORGANIZATIONS', to: '/register' },
    category: 'FOR_ORGANIZATIONS',
    tint: 'bg-tertiary/10 text-tertiary',
    accent: 'bg-tertiary hover:bg-tertiary/90',
  },
  {
    _id: 'svc-government',
    title: 'Government Access',
    ne: 'सरकारी पहुँच',
    description: 'See the full district picture, audit every action and coordinate agencies during a response.',
    features: ['District dashboards', 'Complete audit trail', 'Exportable analytics'],
    icon: 'government',
    cta: { label: 'GOVERNMENT ACCESS', to: '/login' },
    category: 'FOR_ORGANIZATIONS',
    tint: 'bg-ink/10 text-ink',
    accent: 'bg-ink hover:bg-ink/90',
  },
  {
    _id: 'svc-donate',
    title: 'Donate Supplies',
    ne: 'सामग्री दान गर्नुहोस्',
    description: 'Check what is needed most and pledge supplies, transport or funding to verified relief operations.',
    features: ['Live need list', 'Warehouse network', 'Receipt & proof'],
    icon: 'donate',
    cta: { label: 'DONATE SUPPLIES', to: '/about' },
    category: 'FOR_ORGANIZATIONS',
    tint: 'bg-warning/10 text-warning',
    accent: 'bg-warning hover:bg-warning/90',
  },
  {
    _id: 'svc-warehouse',
    title: 'Warehouse Network',
    ne: 'गोदाम सञ्जाल',
    description: 'Manage relief inventory, transfers and expiry across the shelter and warehouse network in Nepal.',
    features: ['Stock tracking', 'Transfer between hubs', 'Low-stock alerts'],
    icon: 'warehouse',
    cta: { label: 'VIEW WAREHOUSES', to: '/map' },
    category: 'FOR_ORGANIZATIONS',
    tint: 'bg-primary/10 text-primary',
    accent: 'bg-primary hover:bg-primary-dark',
  },
];

export const demoServicesData: ServicesData = {
  categories: demoServicesCategories,
  services: demoServices,
  stats: demoServicesStats,
  isDemo: true,
};