import type { LandingData } from '../types/landingTypes';

export const demoLandingData: LandingData = {
  stats: {
    criticalNeeds: 12,
    verifiedNeeds: 28,
    activeResponses: 5,
    availableShelters: 8,
  },
  needs: [
    {
      _id: 'demo-medical',
      title: 'Medical Assistance',
      needType: 'MEDICAL',
      urgency: 'CRITICAL',
      district: 'Dharan',
      ward: 8,
      affectedPeople: 12,
      createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
      verificationStatus: 'VERIFIED',
      status: 'VERIFIED',
    },
    {
      _id: 'demo-water',
      title: 'Clean Water',
      needType: 'WATER',
      urgency: 'HIGH',
      district: 'Ilam',
      ward: 3,
      affectedPeople: 45,
      createdAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
      verificationStatus: 'VERIFIED',
      status: 'VERIFIED',
    },
    {
      _id: 'demo-shelter',
      title: 'Emergency Shelter',
      needType: 'SHELTER',
      urgency: 'HIGH',
      district: 'Kathmandu',
      ward: 12,
      affectedPeople: 28,
      createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      verificationStatus: 'PENDING',
      status: 'PENDING',
    },
    {
      _id: 'demo-food',
      title: 'Food Supplies',
      needType: 'FOOD',
      urgency: 'MEDIUM',
      district: 'Rasuwa',
      ward: 5,
      affectedPeople: 11,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      verificationStatus: 'VERIFIED',
      status: 'VERIFIED',
    },
    {
      _id: 'demo-clothing',
      title: 'Clothing & Essentials',
      needType: 'CLOTHING',
      urgency: 'MEDIUM',
      district: 'Sindhupalchok',
      ward: 4,
      affectedPeople: 32,
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      verificationStatus: 'IN_PROGRESS',
      status: 'IN_PROGRESS',
    },
  ],
  shelters: [
    {
      _id: 'demo-shelter-1',
      name: 'Community Relief Center',
      district: 'Dharan',
      capacity: 250,
      currentOccupancy: 70,
      status: 'AVAILABLE',
    },
    {
      _id: 'demo-shelter-2',
      name: 'Shree Secondary School',
      district: 'Ilam',
      capacity: 180,
      currentOccupancy: 36,
      status: 'AVAILABLE',
    },
    {
      _id: 'demo-shelter-3',
      name: 'Kasturiya Kanya Campus',
      district: 'Kathmandu',
      capacity: 120,
      currentOccupancy: 102,
      status: 'LIMITED',
    },
  ],
  isDemo: true,
};
