import type { Resource, ResourceCategoryMeta, ResourcesData, ResourcesStats } from '../types/resourcesTypes';

export const demoResourcesCategories: ResourceCategoryMeta[] = [
  {
    id: 'GUIDES',
    label: 'Guides & How-Tos',
    description: 'Step-by-step instructions for every service and situation.',
  },
  {
    id: 'SAFETY',
    label: 'Safety & Preparedness',
    description: 'Checklists and guides that keep your family ready.',
  },
  {
    id: 'FORMS',
    label: 'Templates & Downloads',
    description: 'Ready-to-use forms and printable offline tools.',
  },
  {
    id: 'TRAINING',
    label: 'Training & Videos',
    description: 'Short videos and playbooks for volunteers and responders.',
  },
];

export const demoResourcesStats: ResourcesStats = {
  guides: 28,
  downloads: 15400,
  languages: 3,
  hotlines: 12,
};

export const demoResources: Resource[] = [
  // ── Guides & How-Tos ──────────────────────────────────────────────
  {
    _id: 'res-report',
    title: 'How to Report a Need',
    ne: 'आवश्यकता कसरी रिपोर्ट गर्ने',
    description: 'Follow a simple 4-step walkthrough to report food, water, shelter, medical or evacuation needs — even without internet.',
    icon: 'guide',
    cta: { label: 'REPORT A NEED', to: '/report' },
    category: 'GUIDES',
    format: 'article',
    meta: '5 min read',
    tags: ['Offline capable', 'Add photos', 'Track status'],
    popular: true,
    tint: 'bg-critical/10 text-critical',
    accent: 'bg-critical hover:bg-critical/90',
  },
  {
    _id: 'res-map',
    title: 'Using the Live Relief Map',
    ne: 'प्रत्यक्ष राहत नक्सा प्रयोग गर्ने',
    description: 'Learn to filter verified needs, spot open shelters and track active responses across districts in real time.',
    icon: 'plan',
    cta: { label: 'VIEW LIVE MAP', to: '/map' },
    category: 'GUIDES',
    format: 'article',
    meta: '4 min read',
    tags: ['Filter by need', 'Shelter capacity', 'Mobile ready'],
    tint: 'bg-primary/10 text-primary',
    accent: 'bg-primary hover:bg-primary-dark',
  },
  {
    _id: 'res-shelter-guide',
    title: 'Finding a Shelter Step-by-Step',
    ne: 'आश्रय खोज्ने चरण-चरण',
    description: 'A printable checklist that takes you from checking live capacity to confirming a safe place for your family.',
    icon: 'shelter',
    cta: { label: 'FIND SHELTERS', to: '/shelters' },
    category: 'GUIDES',
    format: 'checklist',
    meta: 'Printable checklist',
    tags: ['Live capacity', 'By district', 'Directions included'],
    tint: 'bg-secondary/10 text-secondary',
    accent: 'bg-secondary hover:bg-secondary/90',
  },
  {
    _id: 'res-missing-guide',
    title: 'Missing Persons: A Family Guide',
    ne: 'बेपत्ता: परिवारका लागि मार्गदर्शन',
    description: 'What to do in the first 24 hours, what details to gather, and how to use the match-and-notify system.',
    icon: 'report',
    cta: { label: 'SEARCH & REPORT', to: '/missing-persons' },
    category: 'GUIDES',
    format: 'article',
    meta: '6 min read',
    tags: ['First 24 hours', 'Photo tips', 'Match alerts'],
    popular: true,
    tint: 'bg-ink/10 text-ink',
    accent: 'bg-ink hover:bg-ink/90',
  },
// ── Safety & Preparedness ─────────────────────────────────────────
  {
    _id: 'res-earthquake',
    title: 'Earthquake Safety: Before, During, After',
    ne: 'भूकम्प सुरक्षा',
    description: 'Drop, cover and hold on — plus how to prepare your home and what to do in the hours after the shaking stops.',
    icon: 'safety',
    cta: { label: 'READ THE GUIDE', to: '/hazards' },
    category: 'SAFETY',
    format: 'article',
    meta: '8 min read',
    tags: ['Drop & cover', 'Home prep', 'After-shock plan'],
    popular: true,
    tint: 'bg-warning/10 text-warning',
    accent: 'bg-warning hover:bg-warning/90',
  },
  {
    _id: 'res-flood',
    title: 'Flood & Landslide Preparedness',
    ne: 'बाढी र पहिरो तयारी',
    description: 'Learn the warning signs, make an evacuation route and protect your documents before the monsoon arrives.',
    icon: 'water',
    cta: { label: 'CHECK ALERTS', to: '/hazards' },
    category: 'SAFETY',
    format: 'article',
    meta: '7 min read',
    tags: ['Warning signs', 'Evacuation route', 'Document safety'],
    tint: 'bg-primary/10 text-primary',
    accent: 'bg-primary hover:bg-primary-dark',
  },
  {
    _id: 'res-family-plan',
    title: 'Family Emergency Plan',
    ne: 'पारिवारिक आपतकालीन योजना',
    description: 'A fill-in-the-blanks plan to agree on meeting points, contacts and one trusted neighbor to check on each other.',
    icon: 'download',
    cta: { label: 'DOWNLOAD PLAN', to: '/shelters' },
    category: 'SAFETY',
    format: 'form',
    meta: 'PDF · 2 pages',
    tags: ['Meeting points', 'Key contacts', 'Fill-in-the-blanks'],
    tint: 'bg-tertiary/10 text-tertiary',
    accent: 'bg-tertiary hover:bg-tertiary/90',
  },
  {
    _id: 'res-firstaid',
    title: 'First Aid Basics',
    ne: 'प्राथमिक उपचार आधारभूत',
    description: 'A 4-minute video covering bleeding, burns, fractures and when it is essential to wait for trained responders.',
    icon: 'firstaid',
    cta: { label: 'WATCH THE VIDEO', to: '/register' },
    category: 'SAFETY',
    format: 'video',
    meta: 'Video · 04:32',
    tags: ['Bleeding', 'Burns', 'Fractures'],
    tint: 'bg-critical/10 text-critical',
    accent: 'bg-critical hover:bg-critical/90',
  },
  {
    _id: 'res-contacts',
    title: 'Emergency Contact Card',
    ne: 'आपतकालीन सम्पर्क कार्ड',
    description: 'Print and fill this wallet card with police, ambulance, shelter and local volunteer helplines for Nepal.',
    icon: 'helpline',
    cta: { label: 'GET THE CARD', to: '/report' },
    category: 'SAFETY',
    format: 'contact',
    meta: 'PDF · 1 page',
    tags: ['Print & fill', 'Wallet size', 'नेपाली + English'],
    popular: true,
    tint: 'bg-success/10 text-success',
    accent: 'bg-success hover:bg-success/90',
  },

  // ── Templates & Downloads ─────────────────────────────────────────
  {
    _id: 'res-volunteer-kit',
    title: 'Volunteer Registration Kit',
    ne: 'स्वयंसेवक दर्ता किट',
    description: 'Everything a new volunteer needs: a registration form, ID checklist, code of conduct and a district pick-list.',
    icon: 'form',
    cta: { label: 'JOIN THE RESPONSE', to: '/register' },
    category: 'FORMS',
    format: 'form',
    meta: 'PDF · 4 pages',
    tags: ['Registration form', 'Code of conduct', 'District list'],
    tint: 'bg-success/10 text-success',
    accent: 'bg-success hover:bg-success/90',
  },
  {
    _id: 'res-need-survey',
    title: 'Community Need Survey',
    ne: 'सामुदायिक आवश्यकता सर्वेक्षण',
    description: 'A structured form volunteers can use offline to capture household needs and photo evidence in the field.',
    icon: 'checklist',
    cta: { label: 'VIEW SAMPLE', to: '/report' },
    category: 'FORMS',
    format: 'form',
    meta: 'Form · 3 sections',
    tags: ['Works offline', 'Photo evidence', 'Household needs'],
    tint: 'bg-tertiary/10 text-tertiary',
    accent: 'bg-tertiary hover:bg-tertiary/90',
  },
  {
    _id: 'res-donation-form',
    title: 'Donation Pledge Form',
    ne: 'दान प्रतिबद्धता फारम',
    description: 'Pledge supplies, transport or funding with delivery windows and warehouse drop-off points for each district.',
    icon: 'kit',
    cta: { label: 'DONATE SUPPLIES', to: '/about' },
    category: 'FORMS',
    format: 'form',
    meta: 'PDF · 2 pages',
    tags: ['Supplies pledge', 'Delivery windows', 'Warehouse drop-off'],
    tint: 'bg-warning/10 text-warning',
    accent: 'bg-warning hover:bg-warning/90',
  },

  // ── Training & Videos ─────────────────────────────────────────────
  {
    _id: 'res-onboarding',
    title: 'Volunteer Onboarding Video',
    ne: 'स्वयंसेवक तालिम भिडियो',
    description: 'A short orientation on how reports are verified, how claims work and how to stay safe while helping.',
    icon: 'video',
    cta: { label: 'WATCH NOW', to: '/register' },
    category: 'TRAINING',
    format: 'video',
    meta: 'Video · 06:10',
    tags: ['Verification', 'Claims basics', 'Field safety'],
    popular: true,
    tint: 'bg-primary/10 text-primary',
    accent: 'bg-primary hover:bg-primary-dark',
  },
  {
    _id: 'res-ngo-playbook',
    title: 'NGO Coordination Playbook',
    ne: 'संस्था समन्वय पुस्तिका',
    description: 'A field guide for NGOs and government teams on claims, delivery proof and impact reporting standards.',
    icon: 'community',
    cta: { label: 'OPEN PLAYBOOK', to: '/login' },
    category: 'TRAINING',
    format: 'article',
    meta: '12 min read',
    tags: ['Claims', 'Delivery proof', 'Impact reports'],
    tint: 'bg-ink/10 text-ink',
    accent: 'bg-ink hover:bg-ink/90',
  },
];

export const demoResourcesData: ResourcesData = {
  categories: demoResourcesCategories,
  resources: demoResources,
  stats: demoResourcesStats,
  isDemo: true,
};