import type { HowData, HowRole, HowStats, HowStep, HowVerifyPoint } from '../types/howTypes';

export const demoHowStats: HowStats = {
  provinces: 7,
  districts: 77,
  avgVerifyMinutes: 30,
  avgResolveDays: 2,
  proofRate: 98,
};

export const demoHowSteps: HowStep[] = [
  {
    _id: 'step-report',
    step: '01',
    title: 'REPORT',
    ne: 'रिपोर्ट गर्नुहोस्',
    description: 'Tell us what is needed — one report, in minutes, from any device or through the free hotline.',
    timeline: 'In minutes',
    actions: ['Online form or hotline', 'Works fully offline', 'Location pin + photo'],
    icon: 'report',
    tint: 'bg-primary/10 text-primary',
  },
  {
    _id: 'step-verify',
    step: '02',
    title: 'VERIFY',
    ne: 'प्रमाणीकरण',
    description: 'A trained local volunteer confirms the situation on the ground before anything moves.',
    timeline: 'Within 30 min',
    actions: ['Local volunteer check', 'Duplicates merged', 'Status: verified'],
    icon: 'verify',
    tint: 'bg-secondary/10 text-secondary',
  },
  {
    _id: 'step-claim',
    step: '03',
    title: 'CLAIM',
    ne: 'जिम्मा लिने',
    description: 'An NGO, warehouse or government team takes responsibility and plans the response.',
    timeline: 'Same day',
    actions: ['Smart claim queue', 'Capacity checked', 'Response owner assigned'],
    icon: 'claim',
    tint: 'bg-tertiary/10 text-tertiary',
  },
  {
    _id: 'step-deliver',
    step: '04',
    title: 'DELIVER',
    ne: 'डेलिभरी',
    description: 'Supplies and support arrive with photo proof, while the family follows along live.',
    timeline: 'Tracked live',
    actions: ['Route & team planned', 'Photo proof at handover', 'Live status updates'],
    icon: 'deliver',
    tint: 'bg-warning/10 text-warning',
  },
  {
    _id: 'step-resolve',
    step: '05',
    title: 'RESOLVE',
    ne: 'समाधान',
    description: 'The family confirms help arrived and the need is closed publicly for everyone to see.',
    timeline: 'Until confirmed',
    actions: ['Recipient confirmation', 'Need marked resolved', 'Audit trail complete'],
    icon: 'resolve',
    tint: 'bg-success/10 text-success',
  },
];

export const demoHowRoles: HowRole[] = [
  {
    _id: 'role-people',
    audience: 'PEOPLE',
    title: 'People & Families',
    ne: 'जनता र परिवारहरू',
    description: 'How you get help when you need it most.',
    icon: 'people',
    tint: 'bg-primary/10 text-primary',
    btn: 'bg-primary hover:bg-primary-dark',
    cta: 'REPORT A NEED',
    to: '/report',
    steps: ['Report once — online or offline', 'Volunteers verify your need', 'Follow every delivery until resolved'],
  },
  {
    _id: 'role-volunteers',
    audience: 'VOLUNTEERS',
    title: 'Volunteers',
    ne: 'स्वयंसेवकहरू',
    description: 'How you verify, deliver and build trust in your community.',
    icon: 'volunteer',
    tint: 'bg-success/10 text-success',
    btn: 'bg-success hover:bg-success/90',
    cta: 'BECOME A VOLUNTEER',
    to: '/register',
    steps: ['Join and complete short training', 'Verify genuine needs nearby', 'Earn a public trust score'],
  },
  {
    _id: 'role-orgs',
    audience: 'ORGANIZATIONS',
    title: 'NGOs & Government',
    ne: 'संस्था र सरकार',
    description: 'How organizations coordinate verified relief with full accountability.',
    icon: 'org',
    tint: 'bg-tertiary/10 text-tertiary',
    btn: 'bg-tertiary hover:bg-tertiary/90',
    cta: 'FOR ORGANIZATIONS',
    to: '/register',
    steps: ['Claim verified needs in your area', 'Coordinate warehouses & deliveries', 'Prove impact with photo proof'],
  },
];

export const demoHowVerifyPoints: HowVerifyPoint[] = [
  {
    _id: 'vp-volunteer',
    title: 'Volunteer verification',
    ne: 'स्थानीय प्रमाणीकरण',
    description: 'Trained local volunteers confirm every need on the ground before it moves into the response flow.',
    icon: 'verify',
    tint: 'bg-secondary/10 text-secondary',
  },
  {
    _id: 'vp-proof',
    title: 'Photo proof',
    ne: 'फोटो प्रमाण',
    description: 'Every delivery is captured with photo evidence at handover, so the help can actually be seen arriving.',
    icon: 'proof',
    tint: 'bg-warning/10 text-warning',
  },
  {
    _id: 'vp-score',
    title: 'Trust score',
    ne: 'विश्वास स्कोर',
    description: 'Volunteers and organizations build a public trust record with every verified action they complete.',
    icon: 'score',
    tint: 'bg-primary/10 text-primary',
  },
  {
    _id: 'vp-audit',
    title: 'Public audit trail',
    ne: 'सार्वजनिक अभिलेख',
    description: 'Every report, claim and delivery is time-stamped and visible — nothing is lost in a private inbox.',
    icon: 'audit',
    tint: 'bg-success/10 text-success',
  },
];

export const demoHowData: HowData = {
  stats: demoHowStats,
  steps: demoHowSteps,
  roles: demoHowRoles,
  verifyPoints: demoHowVerifyPoints,
  isDemo: true,
};